### PR TITLE
if we are running http then allow http url

### LINKED ISSUE #1: Don't require https for TFS
The restriction for https should be based off what the current site is running as I think. For on-premises we are running as http://tfs and wanting to show internal sites so https is not as much as a problem.

### PR DESCRIPTION
**Pull request by Gordon-Beeming**
This would fix #1 that I logged =D

### CODE REVIEW

**Comment by Gordon-Beeming** [comment]
Sorry this would fix #1 that I logged =D

**Comment by areve** [comment]
Thanks for your contribution
I did wonder about this when I added the test. It'd be good to support http: too. Were you able to test that this code works? If you are using http://tfs is the iframe that hosts the widget configuration pane also on https?

I think it may be less risky to remove the http validation and just add a note to the bottom instead.

**Comment by areve** [comment]
I've updated the software to no longer do this validation. Thanks you for your contribution, please let me know how you get on.

**Comment by Gordon-Beeming** [comment]
Hi, I tested the change on http only using http. I also tested adding a https page and it worked. 

I think if the site is running as https if we allow http the browser might see that as insecure.

Thanks again for the awesome extension =)

**Pull request closed without merging**
